### ISSUE TITLE
Middleware order problemi

### ISSUE THREAD

**Issue by BatuhanK** [XEngine/express-starter#1]
Selam,
Mongoose ve express ile rest calisirken hazirladigim bir boilerplate var, bunu da diger projelerimde ihtiyacim olursa kullanmayi dusunuyorum bu yuzden  oncelikle eline saglik diyorum vakit ayirdigin icin tesekkurler :)

Repoyu forklayip bir takim degisiklikler yapmayi dusunuyorum, ilk gozume carpan global middlewarelerin express'e bind edildigi yerde bir order mekanizmasi yok fakat bazi middleware'ler digerinden once veya sonra gelmek zorunda olabilir (cookieParser/session gibi). Bununla ilgili olarak orada dosya isimlerine aws'nin elasticbeanstalk'da yaptigi sekilde `01.cookieParser.js` `55.session.js` `11053.helmet.js` seklinde prefix atabilir ve o siraya gore load edebiliriz.

Bunun icin senin aklina gelen baska bir yontem varsa onu da uygulayabiliriz. (Belki export ederken priorty verilebilir)

**Comment by XEngine** [comment]
@BatuhanK 
Middleware lar config klasörü içerisinde ki middleware.js dosyasındaki array aracılığı ile express e aktarılır. Yani aslında bir orderı var.

**Comment by BatuhanK** [comment]
@XEngine aa evet, ben git uzerinden projeye bakmaya calistigim icin atlamisim :) ustteki controllerlar ile ayni sekilde aktariliyor sandim 👍
